 
-- DROP THE TABLE USER_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS USER_T;

-- CREATE A TABLE TO HOLD INFORMATION ON USERS
-- HAWKID IS THE PRIMARY KEY
-- FIRSTNAME, LASTNAME, EMAIL, AND ROLL CAN NOT BE NULL
CREATE TABLE USER_T(
    HAWKID VARCHAR(255) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	STUDENT BIT NOT NULL,
	TUTOR BIT NOT NULL),
	PROFESSOR BIT NOT NULL,
	ADMIN BIT NOT NULL,
	NICK_NAME VARCHAR(255),
	PHONE_NUMBER INT(10),
PRIMARY KEY (HAWKID));
 
 -- DROP THE TABLE STUDENT_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS STUDENT_T;

-- CREATE A TABLE TO HOLD INFORMATION ON STUDENTS
-- HAWKID IS THE PRIMARY KEY AND FORGEIN KEY TO USER_T
-- ALLOC_SESSIONS CAN NOT BE NULL
CREATE TABLE STUDENT_T(
    HAWKID VARCHAR(255) NOT NULL,
	ALLOC_SESSIONS INT(2) NOT NULL,
PRIMARY KEY (HAWKID),
FOREIGN KEY (HAWKID) REFERENCES USER_T(HAWKID));

 -- DROP THE TABLE TUTOR_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS TUTOR_T;

-- CREATE A TABLE TO HOLD INFORMATION ON TUTORS
-- HAWKID IS THE PRIMARY KEY AND FORGEIN KEY TO USER_T
-- ALLOC_SESSIONS CAN NOT BE NULL
CREATE TABLE TUTOR_T(
    HAWKID VARCHAR(255) NOT NULL,
	AVAILABILITY INT(2) NOT NULL, -- NEED TO ASK SEGRE AT NEXT MEETING BEST WAY TO STORE THIS INFORMATION
PRIMARY KEY (HAWKID),
FOREIGN KEY (HAWKID) REFERENCES USER_T(HAWKID));

 -- DROP THE TABLE COURSE_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS COURSE_T;

-- CREATE A TABLE TO HOLD INFORMATION ON COURSES
-- COURSE_ID IS THE PRIMARY KEY
-- COURSE_NAME AND SEMESTER CAN NOT BE NULL
CREATE TABLE COURSE_T(
	COURSE_ID INT(8) NOT NULL AUTO_INCREMENT;
	COURSE_NAME VARCHAR(255) NOT NULL;
	SEMESTER VARCHAR(12) NOT NULL;
PRIMARY KEY (COURSE_ID));