-- SQL File for tutorCS

-- DROP THE TABLE SCHEDULED_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS SCHEDULED_T;

-- DROP THE TABLE SESSION_T IF IT ALREADY EXISTS 
DROP TABLE IF EXISTS SESSION_T;

-- DROP THE TABLE AVAILABILITY_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS AVAILABILITY_T;

-- DROP THE TABLE MATERIALS_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS MATERIALS_T;

-- DROP THE TABLE TEACHES_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS TEACHES_T;

-- DROP THE TABLE TUTORS_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS TUTORS_T;

-- DROP THE TABLE ENROLLED_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS ENROLLED_T;

-- DROP THE TABLE COURSE_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS COURSE_T;

-- DROP THE TABLE TUTOR_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS TUTOR_T;

 -- DROP THE TABLE STUDENT_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS STUDENT_T;

-- DROP THE TABLE USER_T IF IT ALREADY EXISTS
DROP TABLE IF EXISTS USER_T;

-- DROP THE TABLE ACCOUNT_T IF IT ALREADY EXITIS
DROP TABLE IF EXISTS ACCOUNT_T;

-- CREATE A TABLE THAT HOLDS ACCOUNTS CREATED
CREATE TABLE ACCOUNT_T(
  	HAWKID VARCHAR(255) NOT NULL,
  	HASHEDPASS VARCHAR(255) NOT NULL,
PRIMARY KEY (HAWKID));


-- CREATE A TABLE TO HOLD INFORMATION ON USERS
-- HAWKID IS THE PRIMARY KEY
-- FIRSTNAME, LASTNAME, EMAIL, AND ROLL CAN NOT BE NULL
-- BR: A USER MUST BE AT LEAST A STUDENT, PROFESSOR, TUTOR, OR ADMIN
-- BR: A USER MAY BE A TUTOR AND A STUDENT FOR DIFFERENT COURSES
-- BR: A USER MAY BE A PROFESSOR FOR A COURSE AND AN ADMIN FOR THE SYSTEM
-- BR: A USER CAN NOT BE A (STUDENT OR TUTOR) AND A (PROFESSOR OR ADMIN)
CREATE TABLE USER_T(
    HAWKID VARCHAR(255) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	STUDENT BIT NOT NULL,
	TUTOR BIT NOT NULL,
	PROFESSOR BIT NOT NULL,
	ADMIN BIT NOT NULL,
	NICK_NAME VARCHAR(255),
	PHONE_NUMBER INT(10),
	PICTURE VARCHAR(255),
PRIMARY KEY (HAWKID),
FOREIGN KEY (HAWKID) REFERENCES ACCOUNT_T(HAWKID));
 
-- CREATE A TABLE TO HOLD INFORMATION ON STUDENTS
-- HAWKID IS THE PRIMARY KEY AND FORGEIN KEY TO USER_T
-- ALLOC_SESSIONS CAN NOT BE NULL
CREATE TABLE STUDENT_T(
    HAWKID VARCHAR(255) NOT NULL,
	ALLOC_SESSIONS INT(2) NOT NULL,
PRIMARY KEY (HAWKID),
FOREIGN KEY (HAWKID) REFERENCES USER_T(HAWKID));

-- CREATE A TABLE TO HOLD INFORMATION ON TUTORS
-- HAWKID IS THE PRIMARY KEY AND FORGEIN KEY TO USER_T
-- A TUTOR MUST HAVE A BIO AND CAN NOT BE NULL
CREATE TABLE TUTOR_T(
    HAWKID VARCHAR(255) NOT NULL,
	BIO TEXT NOT NULL, -- NEED TO ASK SEGRE AT NEXT MEETING BEST WAY TO STORE THIS INFORMATION
PRIMARY KEY (HAWKID),
FOREIGN KEY (HAWKID) REFERENCES USER_T(HAWKID));

-- CREATE A TABLE TO HOLD INFORMATION ON COURSES
-- COURSE_ID IS THE PRIMARY KEY
-- COURSE_NAME AND SEMESTER CAN NOT BE NULL
-- BR: A COURSE CAN REPEAT IN MULTIPLE SEMESTERS
CREATE TABLE COURSE_T(
	COURSE_ID INT(8) NOT NULL AUTO_INCREMENT,
	COURSE_NAME VARCHAR(255) NOT NULL,
	SEMESTER VARCHAR(12) NOT NULL,
PRIMARY KEY (COURSE_ID));

-- CREATE A TABLE TO HOLD INFORMATION ON STUDENTS THAT ARE ENROLLED IN ONE OR MANY COURSES
-- COURSE_ID AND HAWKID ARE PRIMARY KEYS
-- BR: A STUDENT MUST BE ENROLLED IN AT LEAST ONE COURSE
CREATE TABLE ENROLLED_T(
	HAWKID VARCHAR(255) NOT NULL,
	COURSE_ID INT(8) NOT NULL,
PRIMARY KEY (HAWKID, COURSE_ID),
FOREIGN KEY (HAWKID) REFERENCES STUDENT_T(HAWKID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE_T(COURSE_ID));

-- CREATE A TABLE TO HOLD INFORMATION ON WHICH COURSES A TUTOR TUTORS FOR
-- COURSE_ID AND HAWKID ARE PRIMARY KEYS
-- BR: A TUTOR MUST TUTOR AT LEAST ONE COURSE
CREATE TABLE TUTORS_T(
	HAWKID VARCHAR(255) NOT NULL,
	COURSE_ID INT(8) NOT NULL,
PRIMARY KEY (HAWKID, COURSE_ID),
FOREIGN KEY (HAWKID) REFERENCES TUTOR_T(HAWKID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE_T(COURSE_ID));

-- CREATE A TABLE TO HOLD INFORMATION ON WHICH COURSES A PROFESSOR TEACHES
-- COURSE_ID AND HAWKID ARE PRIMARY KEYS
-- BR: A PROFESSOR MUST TEACH AT LEAST ONE COURSE
CREATE TABLE TEACHES_T(
	HAWKID VARCHAR(255) NOT NULL,
	COURSE_ID INT(8) NOT NULL,
PRIMARY KEY (HAWKID, COURSE_ID),
FOREIGN KEY (HAWKID) REFERENCES USER_T(HAWKID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE_T(COURSE_ID));

-- CREATE A TABLE THAT HOLDS MATERIALS THAT ARE USED FOR A COURSE
-- MATERIAL_ID IS THE PRIMARY KEY
-- COURSE_ID FOREIGN KEY TO COURSE_T
-- MATERIAL_NAME IS NOT NULL
-- BR: A MATERIAL ITEM MUST BE ASSIGNED WITH ONE COURSE
CREATE TABLE MATERIALS_T(
	MATERIAL_ID INT(10) NOT NULL AUTO_INCREMENT,
	COURSE_ID INT(8) NOT NULL,
	MATERIAL_NAME VARCHAR(255) NOT NULL,
	MATERIAL_DESC TEXT,
	FILE VARCHAR(255),
PRIMARY KEY (MATERIAL_ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE_T(COURSE_ID));

-- CREATE A TABLE THAT HOLDS STANDARD AVAILABILITY OF TUTORS WEEK TO WEEK
-- HAWKID IS THE PRIMARY KEY AND REFERENCES HAWKID IN TUTOR_T
CREATE TABLE AVAILABILITY_T(
	HAWKID VARCHAR(255) NOT NULL,
	DAY_OF_WEEK VARCHAR(10) NOT NULL,
	AVAILABLE BIT NOT NULL,
	TIME_START TIME,
	TIME_STOP TIME,
PRIMARY KEY (HAWKID),
FOREIGN KEY (HAWKID) REFERENCES TUTOR_T(HAWKID)
);

-- CREATE A TABLE THAT HOLDS INFORMATION OF AVAILABLE TUTORING SESSIONS THAT AVAILABLE
-- SESSION_ID IS THE PRIMARY KEY
-- TUTOR_HAWKID IS FORGEIN KEY FROM TUTOR_T
-- COURSE_ID IS A FORGEIN KEY FROM COURSE_T
-- ALL ATTRIBUTES ARE NOT NULL AS THEY ARE ALL REQUIRED TO CREATE A SESSION
-- BR: A SESSION MUST BE FOR ONE COURSE
-- BR: A SESSION MUST HAVE ONE TUTOR
-- BR: A TUTOR MUST CREATE AT LEAST ONE OPEN SESSION
-- BR: A SESSION END TIME MUST BE 20 MINUTES AFTER START
CREATE TABLE SESSION_T(
	SESSION_ID INT(6) NOT NULL AUTO_INCREMENT,
	TUTOR_HAWKID VARCHAR(255) NOT NULL,
	COURSE_ID INT(8) NOT NULL,
	SESSION_DATE DATE NOT NULL,
	SESSION_START_TIME TIME NOT NULL,
	SESSION_END_TIME TIME NOT NULL,
	SCHEDULED BIT NOT NULL,
PRIMARY KEY (SESSION_ID),
FOREIGN KEY (TUTOR_HAWKID) REFERENCES TUTOR_T(HAWKID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE_T(COURSE_ID));

-- CREATE A TABLE THAT HOLDS SCHEDULED TUTORING SESSIONS AND KEEPS TRACK OF IF THEY WHERE COMPLETED OR CANCELED AND BY WHOM
-- BR: A SCHEDULED SESSION MUST BE WITH ONE STUDENT
-- BR: A STUDENT CAN HAVE MANY SCHEDULED SESSIONS
-- BR: A SESSION MUST HAVE A MATERIAL_ID OR A COMMENT SUBMITTED BY STUDENT
--
CREATE TABLE SCHEDULED_T(
	SESSION_ID INT(6) NOT NULL,
	STUD_HAWKID VARCHAR(255) NOT NULL,
	MATERIAL_ID INT(10),
	COMPLETED BIT NOT NULL,
	CANC_BY_TUT BIT NOT NULL,
	CANC_BY_STUD BIT NOT NULL,
	COMMENTS TEXT,
PRIMARY KEY (SESSION_ID),
FOREIGN KEY (SESSION_ID) REFERENCES SESSION_T(SESSION_ID),
FOREIGN KEY (STUD_HAWKID) REFERENCES STUDENT_T(HAWKID),
FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIALS_T(MATERIAL_ID));

-- INSERT TEST ACCOUNT HAWKID AND HASHEDPASS
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_a', '$2a$12$Lrk4B17hYdNR7VoZkGCEyeenyPhXkLNMeLV2h96sXgv6BEDx2Ih3a');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_p', '$2a$12$poDq6bPlKmR6D3l67jKqReMW8YzLelLhV14DP7HkgIQNFat4B0SM6');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_pa', '$2a$12$d09Z8y2rhpcvXFYJgmH/T.HKuexRQoJ7QLQMUiMs2eon1Zo5cdLUO');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_s', '$2a$12$BLgGyUtUGh3RcNw83tKtF.H1FcRd07YJ1Wdz/PIbQw.UEbaZLS1D6');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_st', '$2a$12$L3YjY4vI53xTZGWpGmOXueeWDXEjoPL.dbc0PA73B3CRJNY3I5hqG');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_t', '$2a$12$4B2CjTgl9RpSAMK..8523e8QWf3UZ5aquDwJ4e5kLOkpVCOgZiMUS');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_p', '$2a$12$l6pvCG9N5ML.xUF66hBlceOK8a8561YVQ/m1Ws1Gic2ddeWv/Myqq');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_pa', '$2a$12$DG4kRS41sx2QGpvPnWt03uCjaWy02Bip3qI509xvog2SqCfRaxBJW');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_s', '$2a$12$DL.LXgy9C5gDcJY/pV3jVeuBNXkF66WPQvnPxBtjqKYfpej1cCkPW');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_st', '$2a$12$a570sf3czjTtOosY3iwZauvjnyUIZt4prXLYadxM1EO07tuM2iAfS');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_t', '$2a$12$SY7Od9XmlxFQc55.BPD47.31GiqMu.Sq4FrPtf36oYZ/9QovnVme2');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_a', '$2a$12$1PdSfWSPQ80cy9VRC2N7MucjWjTbHxk1IspUEhyxsLVGU.VvZoSh.');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_p', '$2a$12$F/kH7dS6c4tbQJ7KG5RMQebV44Q8VWPPdE2sd8YdOZel55hEur2KS');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_pa', '$2a$12$3jRW6Kxo9ZmyVPx7AmHWCOGkgTNT2RhCoGctb/5ko7hp1mwytkoLa');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_s', '$2a$12$uQmcmNFbJG27MONEfDECxO2f70eVv4qtFr6iMEw2V0ufDTc6vivVa');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_st', '$2a$12$cQn05vbcapLWbAKcTZtC0.7BNOcnz3yPv9ah9F0zwc7tCywpqNKq6'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_t', '$2a$12$XQq344mm9LrKvdcSCxU2Cevhqjib0X2TaI2VOh/0VDs3/qsHTyeo.');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_a', '$2a$12$boz22LtbGdwrxieoAsOaQO8PZnGHexL7mcN2PFZOVkTpiC1IRcO26');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_p', '$2a$12$fLNkchDhOtArx4eCnf1meuUMy1hC8LvfQNJVxmohc.nXknUxzRQ/2');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_pa', '$2a$12$99iyGkUAmSOJU0sGlcNRIO0lthc3NaY8giKtOh7Oa8h57Vug7yrn2'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_s', '$2a$12$jmHJSgtf.Y0EE46PKaW4NOBMW4Jdxa.sTpaRi79FX6beL497hY8vi');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_st', '$2a$12$rcuJeSdOUR1yJ8xImNcOeOGKhoYWd9Z1TtFXQsw7mrFdEJ8EwRIWa'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_t', '$2a$12$Cja1.G./Abao/e7l8DLRM.9iFcDa2q2/BbUstDPhwYqCDOdFdtH3q');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_a', '$2a$12$Moprannq8V6tzfBL/eRS3uF9DlYORbz3ANHuu9pJaioYMQu1/t6We'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_p', '$2a$12$c9m4hRNCgNjfbF54/56iMOiJkk0/GdnmT6LqeL2xUjb64rmfGsuty');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_pa', '$2a$12$8n1inAaqpjGvzl02Aolj1eBxN9TPVUndxooxBNe7eriabGA2Vxeve'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_s', '$2a$12$zlQYnxyde1SWdRQ2.CHyQePQTVv25L115HhgGS2VRj7m95yLQ7ySi');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_st', '$2a$12$8e2a4gqJZUnJOLTdrL1ja.iXQ3rOFetEuxvWPyK9VcLJf8RBfgB22'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_t', '$2a$12$WYvPFWkrXEi/Ww5ZXq2deeh2stvY.DU9mxQpyG9vZ57Wr42/9WVJ2');
 