-- SQL FOR TEST DATA

-- INSERT TEST ACCOUNT HAWKID AND HASHEDPASS
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_a', '$2a$12$Lrk4B17hYdNR7VoZkGCEyeenyPhXkLNMeLV2h96sXgv6BEDx2Ih3a');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_p', '$2a$12$poDq6bPlKmR6D3l67jKqReMW8YzLelLhV14DP7HkgIQNFat4B0SM6');

INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_pa', '$2a$12$d09Z8y2rhpcvXFYJgmH/T.HKuexRQoJ7QLQMUiMs2eon1Zo5cdLUO');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_s', '$2a$12$BLgGyUtUGh3RcNw83tKtF.H1FcRd07YJ1Wdz/PIbQw.UEbaZLS1D6');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_st', '$2a$12$L3YjY4vI53xTZGWpGmOXueeWDXEjoPL.dbc0PA73B3CRJNY3I5hqG');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cgitzlaff_t', '$2a$12$4B2CjTgl9RpSAMK..8523e8QWf3UZ5aquDwJ4e5kLOkpVCOgZiMUS');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_p', '$2a$12$l6pvCG9N5ML.xUF66hBlceOK8a8561YVQ/m1Ws1Gic2ddeWv/Myqq');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_pa', '$2a$12$DG4kRS41sx2QGpvPnWt03uCjaWy02Bip3qI509xvog2SqCfRaxBJW');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_s', '$2a$12$DL.LXgy9C5gDcJY/pV3jVeuBNXkF66WPQvnPxBtjqKYfpej1cCkPW');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_st', '$2a$12$a570sf3czjTtOosY3iwZauvjnyUIZt4prXLYadxM1EO07tuM2iAfS');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('cmurphy3_t', '$2a$12$SY7Od9XmlxFQc55.BPD47.31GiqMu.Sq4FrPtf36oYZ/9QovnVme2');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_a', '$2a$12$1PdSfWSPQ80cy9VRC2N7MucjWjTbHxk1IspUEhyxsLVGU.VvZoSh.');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_p', '$2a$12$F/kH7dS6c4tbQJ7KG5RMQebV44Q8VWPPdE2sd8YdOZel55hEur2KS');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_pa', '$2a$12$3jRW6Kxo9ZmyVPx7AmHWCOGkgTNT2RhCoGctb/5ko7hp1mwytkoLa');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_s', '$2a$12$uQmcmNFbJG27MONEfDECxO2f70eVv4qtFr6iMEw2V0ufDTc6vivVa');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_st', '$2a$12$cQn05vbcapLWbAKcTZtC0.7BNOcnz3yPv9ah9F0zwc7tCywpqNKq6'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('hourcade_t', '$2a$12$XQq344mm9LrKvdcSCxU2Cevhqjib0X2TaI2VOh/0VDs3/qsHTyeo.');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_a', '$2a$12$boz22LtbGdwrxieoAsOaQO8PZnGHexL7mcN2PFZOVkTpiC1IRcO26');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_p', '$2a$12$fLNkchDhOtArx4eCnf1meuUMy1hC8LvfQNJVxmohc.nXknUxzRQ/2');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_pa', '$2a$12$99iyGkUAmSOJU0sGlcNRIO0lthc3NaY8giKtOh7Oa8h57Vug7yrn2'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_s', '$2a$12$jmHJSgtf.Y0EE46PKaW4NOBMW4Jdxa.sTpaRi79FX6beL497hY8vi');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_st', '$2a$12$rcuJeSdOUR1yJ8xImNcOeOGKhoYWd9Z1TtFXQsw7mrFdEJ8EwRIWa'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('segre_t', '$2a$12$Cja1.G./Abao/e7l8DLRM.9iFcDa2q2/BbUstDPhwYqCDOdFdtH3q');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_a', '$2a$12$Moprannq8V6tzfBL/eRS3uF9DlYORbz3ANHuu9pJaioYMQu1/t6We'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_p', '$2a$12$c9m4hRNCgNjfbF54/56iMOiJkk0/GdnmT6LqeL2xUjb64rmfGsuty');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_pa', '$2a$12$8n1inAaqpjGvzl02Aolj1eBxN9TPVUndxooxBNe7eriabGA2Vxeve'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_s', '$2a$12$zlQYnxyde1SWdRQ2.CHyQePQTVv25L115HhgGS2VRj7m95yLQ7ySi');
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_st', '$2a$12$8e2a4gqJZUnJOLTdrL1ja.iXQ3rOFetEuxvWPyK9VcLJf8RBfgB22'); 
INSERT INTO ACCOUNT_T (HAWKID, HASHEDPASS) VALUES ('tmesserly_t', '$2a$12$WYvPFWkrXEi/Ww5ZXq2deeh2stvY.DU9mxQpyG9vZ57Wr42/9WVJ2');

-- DEFINE USER ROLES AND INFORMATION



